return {
	{ import = "plugins.ui" }, -- UI plugins
	{ import = "plugins.lsp" }, -- for lspnvim
	{ import = "plugins.helpers" }, -- helping plugins
	{ import = "plugins.statusline" }, -- statusline plugin(lualine)
	{ import = "plugins.treesitter" },
	{ import = "plugins.productivity" }, -- some useful plugins for increasing productivity
	{ import = "plugins.file_explorers" }, -- Plugins related to navigation with files
	{ import = "plugins.navigation-impr" }, -- useful neovim game, to develop the skills of using nvim
	{ import = "plugins.folding" }, -- folding plugin
	{ import = "plugins.new" }, -- some cool new stuff, check that folder to see them
	{ import = "plugins.zen" }, -- zen mode
	{ import = "plugins.debugging" }, -- Debugging
	{ import = "plugins.cmp" }, -- Autocompletion
	{ import = "plugins.utils" }, -- some useful utils, check the folder to see more infos
	{ import = "plugins.language-support.cc" }, -- Supporting for c and cpp
	{ import = "plugins.mason" }, -- Mason tools
	{ import = "plugins.org" }, -- Org
	{ import = "plugins.web" }, -- Web development
	{ import = "plugins.git" }, -- git/github
	{ import = "plugins.splitting" }, -- Split
	{ import = "plugins.flutter" }, -- Flutter
	{ import = "plugins.outliners" }, -- Outliners
	{ import = "plugins.new" }, -- Outliners
	{ import = "plugins.ai" }, -- Add ai stuff to neovim
	{ import = "plugins.uml" }, -- Add ai stuff to neovim
	{ import = "plugins.cp" }, -- Add ai stuff to neovim
	{ import = "plugins.Latex" }, -- Custumize the workflow
	{ import = "plugins.markdown" }, -- Custumize the workflow
	-- { import = "plugins.workflow" }, -- Custumize the workflow
}
